[versions]
guava = "32.1.3-jre"
junit-jupiter = "5.10.1"
apacheCommonsLang = "3.14.0"
jmh = "1.37"


[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
commons-lang = { module = "org.apache.commons:commons-lang3", version.ref = "apacheCommonsLang" }
jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jmh-annotations = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }
